# File: docker-compose.yml
services:
  api-service:
    build:
      context: .
      dockerfile: ./Dockerfile.prod-supabase
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env

    command: bun run start
    restart: unless-stopped