# File: docker-compose.yml
version: '3.8'
services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db.sqlite:/app/db.sqlite
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env

    command: bun run start
    restart: unless-stopped